#include "model-downloader-types.h"

std::vector<ModelInfo> model_infos = {
	{"Afrikaans Mimic3 google-nwu_low (9 speakers)",
	 "vits-mimic3-af_ZA-google-nwu_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-af_ZA-google-nwu_low.tar.bz2",
	   ""}}},
	{"Arabic Piper kareem-low",
	 "vits-piper-ar_JO-kareem-low (1 speaker)",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ar_JO-kareem-low.tar.bz2",
	   ""}}},
	{"Arabic Piper kareem-medium",
	 "vits-piper-ar_JO-kareem-medium (1 speaker)",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ar_JO-kareem-medium.tar.bz2",
	   ""}}},
	{"Bengali Coqui female",
	 "vits-coqui-bn-custom_female (1 speaker)",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-bn-custom_female.tar.bz2",
	   ""}}},
	{"Bengali Mimic3 multi_low",
	 "vits-mimic3-bn-multi_low (16 speakers)",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-bn-multi_low.tar.bz2",
	   ""}}},
	{"Bulgarian Coqui (1 speaker)",
	 "vits-coqui-bg-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-bg-cv.tar.bz2",
	   ""}}},
	{"Cantonese Xiaomaiiwn",
	 "vits-cantonese-hf-xiaomaiiwn",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-cantonese-hf-xiaomaiiwn.tar.bz2",
	   ""}}},
	{"Catalan Piper upc_ona-medium",
	 "vits-piper-ca_ES-upc_ona-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ca_ES-upc_ona-medium.tar.bz2",
	   ""}}},
	{"Catalan Piper upc_ona-x_low",
	 "vits-piper-ca_ES-upc_ona-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ca_ES-upc_ona-x_low.tar.bz2",
	   ""}}},
	{"Catalan Piper upc_pau-x_low",
	 "vits-piper-ca_ES-upc_pau-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ca_ES-upc_pau-x_low.tar.bz2",
	   ""}}},
	{"Chinese abyssinvoker",
	 "vits-zh-hf-abyssinvoker",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-abyssinvoker.tar.bz2",
	   ""}}},
	{"Chinese aishell3",
	 "vits-zh-aishell3",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-aishell3.tar.bz2",
	   ""}}},
	{"Chinese bronya",
	 "vits-zh-hf-bronya",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-bronya.tar.bz2",
	   ""}}},
	{"Chinese doom",
	 "vits-zh-hf-doom",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-doom.tar.bz2",
	   ""}}},
	{"Chinese echo",
	 "vits-zh-hf-echo",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-echo.tar.bz2",
	   ""}}},
	{"Chinese eula",
	 "vits-zh-hf-eula",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-eula.tar.bz2",
	   ""}}},
	{"Chinese fanchen-C",
	 "vits-zh-hf-fanchen-C",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-fanchen-C.tar.bz2",
	   ""}}},
	{"Chinese fanchen-unity",
	 "vits-zh-hf-fanchen-unity",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-fanchen-unity.tar.bz2",
	   ""}}},
	{"Chinese fanchen-wnj",
	 "vits-zh-hf-fanchen-wnj",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-fanchen-wnj.tar.bz2",
	   ""}}},
	{"Chinese fanchen-ZhiHuiLaoZhe_new",
	 "vits-zh-hf-fanchen-ZhiHuiLaoZhe_new",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-fanchen-ZhiHuiLaoZhe_new.tar.bz2",
	   ""}}},
	{"Chinese fanchen-ZhiHuiLaoZhe",
	 "vits-zh-hf-fanchen-ZhiHuiLaoZhe",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-fanchen-ZhiHuiLaoZhe.tar.bz2",
	   ""}}},
	{"Chinese Icefall aishell3",
	 "vits-icefall-zh-aishell3",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-icefall-zh-aishell3.tar.bz2",
	   ""}}},
	{"Chinese keqing",
	 "vits-zh-hf-keqing",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-keqing.tar.bz2",
	   ""}}},
	{"Chinese ll",
	 "sherpa-onnx-vits-zh-ll",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/sherpa-onnx-vits-zh-ll.tar.bz2",
	   ""}}},
	{"Chinese Piper huayan-medium",
	 "vits-piper-zh_CN-huayan-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-zh_CN-huayan-medium.tar.bz2",
	   ""}}},
	{"Chinese theresa",
	 "vits-zh-hf-theresa",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-theresa.tar.bz2",
	   ""}}},
	{"Chinese zenyatta",
	 "vits-zh-hf-zenyatta",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-hf-zenyatta.tar.bz2",
	   ""}}},
	{"Croatian Coqui cv",
	 "vits-coqui-hr-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-hr-cv.tar.bz2",
	   ""}}},
	{"Czech Coqui",
	 "vits-coqui-cs-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-cs-cv.tar.bz2",
	   ""}}},
	{"Czech Piper jirka-low",
	 "vits-piper-cs_CZ-jirka-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-cs_CZ-jirka-low.tar.bz2",
	   ""}}},
	{"Czech Piper jirka-medium",
	 "vits-piper-cs_CZ-jirka-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-cs_CZ-jirka-medium.tar.bz2",
	   ""}}},
	{"Danish Coqui",
	 "vits-coqui-da-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-da-cv.tar.bz2",
	   ""}}},
	{"Danish Piper talesyntese-medium",
	 "vits-piper-da_DK-talesyntese-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-da_DK-talesyntese-medium.tar.bz2",
	   ""}}},
	{"Dutch Coqui css10",
	 "vits-coqui-nl-css10",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-nl-css10.tar.bz2",
	   ""}}},
	{"Dutch Piper mls_5809-low",
	 "vits-piper-nl_NL-mls_5809-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-nl_NL-mls_5809-low.tar.bz2",
	   ""}}},
	{"Dutch Piper mls_7432-low",
	 "vits-piper-nl_NL-mls_7432-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-nl_NL-mls_7432-low.tar.bz2",
	   ""}}},
	{"Dutch Piper mls-medium",
	 "vits-piper-nl_NL-mls-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-nl_NL-mls-medium.tar.bz2",
	   ""}}},
	{"Dutch Piper nathalie-medium",
	 "vits-piper-nl_BE-nathalie-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-nl_BE-nathalie-medium.tar.bz2",
	   ""}}},
	{"Dutch Piper nathalie-x_low",
	 "vits-piper-nl_BE-nathalie-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-nl_BE-nathalie-x_low.tar.bz2",
	   ""}}},
	{"Dutch Piper rdh-medium",
	 "vits-piper-nl_BE-rdh-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-nl_BE-rdh-medium.tar.bz2",
	   ""}}},
	{"Dutch Piper rdh-x_low",
	 "vits-piper-nl_BE-rdh-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-nl_BE-rdh-x_low.tar.bz2",
	   ""}}},
	{"English Coqui ljspeech-neon (1 speaker)",
	 "vits-coqui-en-ljspeech-neon",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-en-ljspeech-neon.tar.bz2",
	   ""}}},
	{"English Coqui ljspeech (1 speaker)",
	 "vits-coqui-en-ljspeech",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-en-ljspeech.tar.bz2",
	   ""}}},
	{"English Coqui vctk (109 speakers)",
	 "vits-coqui-en-vctk",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-en-vctk.tar.bz2",
	   ""}}},
	{"English MMS",
	 "vits-mms-eng",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-eng.tar.bz2",
	   ""}}},
	{"English UK Coqui mai",
	 "vits-coqui-uk-mai",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-uk-mai.tar.bz2",
	   ""}}},
	{"English UK Piper alan-low",
	 "vits-piper-en_GB-alan-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-alan-low.tar.bz2",
	   ""}}},
	{"English UK Piper alan-medium",
	 "vits-piper-en_GB-alan-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-alan-medium.tar.bz2",
	   ""}}},
	{"English UK Piper alba-medium",
	 "vits-piper-en_GB-alba-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-alba-medium.tar.bz2",
	   ""}}},
	{"English UK Piper aru-medium",
	 "vits-piper-en_GB-aru-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-aru-medium.tar.bz2",
	   ""}}},
	{"English UK Piper cori-high",
	 "vits-piper-en_GB-cori-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-cori-high.tar.bz2",
	   ""}}},
	{"English UK Piper cori-medium",
	 "vits-piper-en_GB-cori-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-cori-medium.tar.bz2",
	   ""}}},
	{"English UK Piper jenny_dioco-medium",
	 "vits-piper-en_GB-jenny_dioco-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-jenny_dioco-medium.tar.bz2",
	   ""}}},
	{"English UK Piper northern_english_male-medium",
	 "vits-piper-en_GB-northern_english_male-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-northern_english_male-medium.tar.bz2",
	   ""}}},
	{"English UK Piper semaine-medium (4 speakers)",
	 "vits-piper-en_GB-semaine-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-semaine-medium.tar.bz2",
	   ""}}},
	{"English UK Piper southern_english_female-low",
	 "vits-piper-en_GB-southern_english_female-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-southern_english_female-low.tar.bz2",
	   ""}}},
	{"English UK Piper southern_english_female-medium (6 speakers)",
	 "vits-piper-en_GB-southern_english_female-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-southern_english_female-medium.tar.bz2",
	   ""}}},
	{"English UK Piper southern_english_male-medium (8 speakers)",
	 "vits-piper-en_GB-southern_english_male-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-southern_english_male-medium.tar.bz2",
	   ""}}},
	{"English UK Piper sweetbbak-amy (1 speaker)",
	 "vits-piper-en_GB-sweetbbak-amy",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-sweetbbak-amy.tar.bz2",
	   ""}}},
	{"English UK Piper vctk-medium (109 speakers)",
	 "vits-piper-en_GB-vctk-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_GB-vctk-medium.tar.bz2",
	   ""}}},
	{"English US Icefall ljspeech-low",
	 "vits-icefall-en_US-ljspeech-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-icefall-en_US-ljspeech-low.tar.bz2",
	   ""}}},
	{"English US Icefall ljspeech-medium",
	 "vits-icefall-en_US-ljspeech-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-icefall-en_US-ljspeech-medium.tar.bz2",
	   ""}}},
	{"English US Piper amy-low",
	 "vits-piper-en_US-amy-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-amy-low.tar.bz2",
	   ""}}},
	{"English US Piper amy-medium",
	 "vits-piper-en_US-amy-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-amy-medium.tar.bz2",
	   ""}}},
	{"English US Piper arctic-medium (18 speakers)",
	 "vits-piper-en_US-arctic-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-arctic-medium.tar.bz2",
	   ""}}},
	{"English US Piper bryce-medium (1 speaker)",
	 "vits-piper-en_US-bryce-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-bryce-medium.tar.bz2",
	   ""}}},
	{"English US Piper danny-low",
	 "vits-piper-en_US-danny-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-danny-low.tar.bz2",
	   ""}}},
	{"English US Piper glados (1 speaker)",
	 "vits-piper-en_US-glados",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-glados.tar.bz2",
	   ""}}},
	{"English US Piper hfc_female-medium",
	 "vits-piper-en_US-hfc_female-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-hfc_female-medium.tar.bz2",
	   ""}}},
	{"English US Piper hfc_male-medium",
	 "vits-piper-en_US-hfc_male-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-hfc_male-medium.tar.bz2",
	   ""}}},
	{"English US Piper joe-medium",
	 "vits-piper-en_US-joe-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-joe-medium.tar.bz2",
	   ""}}},
	{"English US Piper john-medium (1 speaker)",
	 "vits-piper-en_US-john-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-john-medium.tar.bz2",
	   ""}}},
	{"English US Piper kathleen-low",
	 "vits-piper-en_US-kathleen-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-kathleen-low.tar.bz2",
	   ""}}},
	{"English US Piper kristin-medium",
	 "vits-piper-en_US-kristin-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-kristin-medium.tar.bz2",
	   ""}}},
	{"English US Piper kusal-medium",
	 "vits-piper-en_US-kusal-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-kusal-medium.tar.bz2",
	   ""}}},
	{"English US Piper l2arctic-medium (24 speakers)",
	 "vits-piper-en_US-l2arctic-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-l2arctic-medium.tar.bz2",
	   ""}}},
	{"English US Piper lessac-high",
	 "vits-piper-en_US-lessac-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-lessac-high.tar.bz2",
	   ""}}},
	{"English US Piper lessac-low",
	 "vits-piper-en_US-lessac-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-lessac-low.tar.bz2",
	   ""}}},
	{"English US Piper lessac-medium",
	 "vits-piper-en_US-lessac-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-lessac-medium.tar.bz2",
	   ""}}},
	{"English US Piper libritts_r-medium (904 speakers)",
	 "vits-piper-en_US-libritts_r-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-libritts_r-medium.tar.bz2",
	   ""}}},
	{"English US Piper libritts-high (904 speakers)",
	 "vits-piper-en_US-libritts-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-libritts-high.tar.bz2",
	   ""}}},
	{"English US Piper ljspeech-high",
	 "vits-piper-en_US-ljspeech-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-ljspeech-high.tar.bz2",
	   ""}}},
	{"English US Piper ljspeech-medium",
	 "vits-piper-en_US-ljspeech-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-ljspeech-medium.tar.bz2",
	   ""}}},
	{"English US Piper norman-medium (1 speaker)",
	 "vits-piper-en_US-norman-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-norman-medium.tar.bz2",
	   ""}}},
	{"English US Piper ryan-high",
	 "vits-piper-en_US-ryan-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-ryan-high.tar.bz2",
	   ""}}},
	{"English US Piper ryan-low",
	 "vits-piper-en_US-ryan-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-ryan-low.tar.bz2",
	   ""}}},
	{"English US Piper ryan-medium",
	 "vits-piper-en_US-ryan-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-ryan-medium.tar.bz2",
	   ""}}},
	{"Estonian Coqui",
	 "vits-coqui-et-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-et-cv.tar.bz2",
	   ""}}},
	{"Finnish Coqui css10",
	 "vits-coqui-fi-css10",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-fi-css10.tar.bz2",
	   ""}}},
	{"Finnish Mimic3 harri-tapani-ylilammi_low",
	 "vits-mimic3-fi_FI-harri-tapani-ylilammi_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-fi_FI-harri-tapani-ylilammi_low.tar.bz2",
	   ""}}},
	{"Finnish Piper harri-low",
	 "vits-piper-fi_FI-harri-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fi_FI-harri-low.tar.bz2",
	   ""}}},
	{"Finnish Piper harri-medium",
	 "vits-piper-fi_FI-harri-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fi_FI-harri-medium.tar.bz2",
	   ""}}},
	{"French Coqui css10",
	 "vits-coqui-fr-css10",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-fr-css10.tar.bz2",
	   ""}}},
	{"French MMS",
	 "vits-mms-fra",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-fra.tar.bz2",
	   ""}}},
	{"French Piper gilles-low",
	 "vits-piper-fr_FR-gilles-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-gilles-low.tar.bz2",
	   ""}}},
	{"French Piper mls_1840-low",
	 "vits-piper-fr_FR-mls_1840-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-mls_1840-low.tar.bz2",
	   ""}}},
	{"French Piper siwis-low",
	 "vits-piper-fr_FR-siwis-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-siwis-low.tar.bz2",
	   ""}}},
	{"French Piper siwis-medium",
	 "vits-piper-fr_FR-siwis-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-siwis-medium.tar.bz2",
	   ""}}},
	{"French Piper tjiho-model1",
	 "vits-piper-fr_FR-tjiho-model1",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-tjiho-model1.tar.bz2",
	   ""}}},
	{"French Piper tjiho-model2",
	 "vits-piper-fr_FR-tjiho-model2",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-tjiho-model2.tar.bz2",
	   ""}}},
	{"French Piper tjiho-model3",
	 "vits-piper-fr_FR-tjiho-model3",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-tjiho-model3.tar.bz2",
	   ""}}},
	{"French Piper tom-medium",
	 "vits-piper-fr_FR-tom-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-tom-medium.tar.bz2",
	   ""}}},
	{"French Piper upmc-medium",
	 "vits-piper-fr_FR-upmc-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-upmc-medium.tar.bz2",
	   ""}}},
	{"Georgian Piper natia-medium",
	 "vits-piper-ka_GE-natia-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ka_GE-natia-medium.tar.bz2",
	   ""}}},
	{"German Coqui",
	 "vits-coqui-de-css10",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-de-css10.tar.bz2",
	   ""}}},
	{"German MMS",
	 "vits-mms-deu",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-deu.tar.bz2",
	   ""}}},
	{"German Piper eva_k-x_low",
	 "vits-piper-de_DE-eva_k-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-eva_k-x_low.tar.bz2",
	   ""}}},
	{"German Piper karlsson-low",
	 "vits-piper-de_DE-karlsson-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-karlsson-low.tar.bz2",
	   ""}}},
	{"German Piper kerstin-low",
	 "vits-piper-de_DE-kerstin-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-kerstin-low.tar.bz2",
	   ""}}},
	{"German Piper pavoque-low",
	 "vits-piper-de_DE-pavoque-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-pavoque-low.tar.bz2",
	   ""}}},
	{"German Piper ramona-low",
	 "vits-piper-de_DE-ramona-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-ramona-low.tar.bz2",
	   ""}}},
	{"German Piper thorsten_emotional-medium",
	 "vits-piper-de_DE-thorsten_emotional-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-thorsten_emotional-medium.tar.bz2",
	   ""}}},
	{"German Piper thorsten-high",
	 "vits-piper-de_DE-thorsten-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-thorsten-high.tar.bz2",
	   ""}}},
	{"German Piper thorsten-low",
	 "vits-piper-de_DE-thorsten-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-thorsten-low.tar.bz2",
	   ""}}},
	{"German Piper thorsten-medium",
	 "vits-piper-de_DE-thorsten-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-thorsten-medium.tar.bz2",
	   ""}}},
	{"Greek Mimic3 rapunzelina_low",
	 "vits-mimic3-el_GR-rapunzelina_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-el_GR-rapunzelina_low.tar.bz2",
	   ""}}},
	{"Greek Piper rapunzelina-low",
	 "vits-piper-el_GR-rapunzelina-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-el_GR-rapunzelina-low.tar.bz2",
	   ""}}},
	{"Gujarati Mimic3 cmu-indic_low",
	 "vits-mimic3-gu_IN-cmu-indic_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-gu_IN-cmu-indic_low.tar.bz2",
	   ""}}},
	{"Hungarian Mimic3 diana-majlinger_low",
	 "vits-mimic3-hu_HU-diana-majlinger_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-hu_HU-diana-majlinger_low.tar.bz2",
	   ""}}},
	{"Hungarian Piper anna-medium",
	 "vits-piper-hu_HU-anna-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-hu_HU-anna-medium.tar.bz2",
	   ""}}},
	{"Hungarian Piper berta-medium",
	 "vits-piper-hu_HU-berta-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-hu_HU-berta-medium.tar.bz2",
	   ""}}},
	{"Hungarian Piper imre-medium",
	 "vits-piper-hu_HU-imre-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-hu_HU-imre-medium.tar.bz2",
	   ""}}},
	{"Icelandic Piper bui-medium",
	 "vits-piper-is_IS-bui-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-is_IS-bui-medium.tar.bz2",
	   ""}}},
	{"Icelandic Piper salka-medium",
	 "vits-piper-is_IS-salka-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-is_IS-salka-medium.tar.bz2",
	   ""}}},
	{"Icelandic Piper steinn-medium",
	 "vits-piper-is_IS-steinn-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-is_IS-steinn-medium.tar.bz2",
	   ""}}},
	{"Icelandic Piper ugla-medium",
	 "vits-piper-is_IS-ugla-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-is_IS-ugla-medium.tar.bz2",
	   ""}}},
	{"Irish Coqui cv",
	 "vits-coqui-ga-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-ga-cv.tar.bz2",
	   ""}}},
	{"Italian Piper paola-medium",
	 "vits-piper-it_IT-paola-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-it_IT-paola-medium.tar.bz2",
	   ""}}},
	{"Italian Piper riccardo-x_low",
	 "vits-piper-it_IT-riccardo-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-it_IT-riccardo-x_low.tar.bz2",
	   ""}}},
	{"Kazakh Piper iseke-x_low",
	 "vits-piper-kk_KZ-iseke-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-kk_KZ-iseke-x_low.tar.bz2",
	   ""}}},
	{"Kazakh Piper issai-high",
	 "vits-piper-kk_KZ-issai-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-kk_KZ-issai-high.tar.bz2",
	   ""}}},
	{"Kazakh Piper raya-x_low",
	 "vits-piper-kk_KZ-raya-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-kk_KZ-raya-x_low.tar.bz2",
	   ""}}},
	{"Korean Mimic3 kss_low",
	 "vits-mimic3-ko_KO-kss_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-ko_KO-kss_low.tar.bz2",
	   ""}}},
	{"Latvian Coqui cv",
	 "vits-coqui-lv-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-lv-cv.tar.bz2",
	   ""}}},
	{"Lithuanian Coqui cv",
	 "vits-coqui-lt-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-lt-cv.tar.bz2",
	   ""}}},
	{"LJSpeech",
	 "vits-ljs",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-ljs.tar.bz2",
	   ""}}},
	{"Luxembourgish Piper marylux-medium",
	 "vits-piper-lb_LU-marylux-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-lb_LU-marylux-medium.tar.bz2",
	   ""}}},
	{"Maltese Coqui cv",
	 "vits-coqui-mt-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-mt-cv.tar.bz2",
	   ""}}},
	{"Nan MMS",
	 "vits-mms-nan",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-nan.tar.bz2",
	   ""}}},
	{"Nepali Mimic3 google_low",
	 "vits-mimic3-ne_NP-ne-google_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-ne_NP-ne-google_low.tar.bz2",
	   ""}}},
	{"Nepali Piper google-medium",
	 "vits-piper-ne_NP-google-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ne_NP-google-medium.tar.bz2",
	   ""}}},
	{"Nepali Piper google-x_low",
	 "vits-piper-ne_NP-google-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ne_NP-google-x_low.tar.bz2",
	   ""}}},
	{"Norwegian Piper talesyntese-medium",
	 "vits-piper-no_NO-talesyntese-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-no_NO-talesyntese-medium.tar.bz2",
	   ""}}},
	{"Persian Mimic3 haaniye_low",
	 "vits-mimic3-fa-haaniye_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-fa-haaniye_low.tar.bz2",
	   ""}}},
	{"Persian Piper amir-medium",
	 "vits-piper-fa_IR-amir-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fa_IR-amir-medium.tar.bz2",
	   ""}}},
	{"Persian Piper gyro-medium",
	 "vits-piper-fa_IR-gyro-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fa_IR-gyro-medium.tar.bz2",
	   ""}}},
	{"Persian Piper haaniye_low",
	 "vits-piper-fa-haaniye_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fa-haaniye_low.tar.bz2",
	   ""}}},
	{"Polish Coqui mai_female",
	 "vits-coqui-pl-mai_female",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-pl-mai_female.tar.bz2",
	   ""}}},
	{"Polish Mimic3 m-ailabs_low",
	 "vits-mimic3-pl_PL-m-ailabs_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-pl_PL-m-ailabs_low.tar.bz2",
	   ""}}},
	{"Polish Piper darkman-medium",
	 "vits-piper-pl_PL-darkman-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-pl_PL-darkman-medium.tar.bz2",
	   ""}}},
	{"Polish Piper gosia-medium",
	 "vits-piper-pl_PL-gosia-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-pl_PL-gosia-medium.tar.bz2",
	   ""}}},
	{"Polish Piper mc_speech-medium",
	 "vits-piper-pl_PL-mc_speech-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-pl_PL-mc_speech-medium.tar.bz2",
	   ""}}},
	{"Polish Piper mls_6892-low",
	 "vits-piper-pl_PL-mls_6892-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-pl_PL-mls_6892-low.tar.bz2",
	   ""}}},
	{"Portugese Coqui cv",
	 "vits-coqui-pt-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-pt-cv.tar.bz2",
	   ""}}},
	{"Portugese Piper edresson-low",
	 "vits-piper-pt_BR-edresson-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-pt_BR-edresson-low.tar.bz2",
	   ""}}},
	{"Portugese Piper faber-medium",
	 "vits-piper-pt_BR-faber-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-pt_BR-faber-medium.tar.bz2",
	   ""}}},
	{"Portugese Piper tugao-medium",
	 "vits-piper-pt_PT-tugao-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-pt_PT-tugao-medium.tar.bz2",
	   ""}}},
	{"Romanian Coqui cv",
	 "vits-coqui-ro-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-ro-cv.tar.bz2",
	   ""}}},
	{"Romanian Piper mihai-medium",
	 "vits-piper-ro_RO-mihai-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ro_RO-mihai-medium.tar.bz2",
	   ""}}},
	{"Russian MMS",
	 "vits-mms-rus",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-rus.tar.bz2",
	   ""}}},
	{"Russian Piper denis-medium",
	 "vits-piper-ru_RU-denis-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ru_RU-denis-medium.tar.bz2",
	   ""}}},
	{"Russian Piper dmitri-medium",
	 "vits-piper-ru_RU-dmitri-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ru_RU-dmitri-medium.tar.bz2",
	   ""}}},
	{"Russian Piper irina-medium",
	 "vits-piper-ru_RU-irina-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ru_RU-irina-medium.tar.bz2",
	   ""}}},
	{"Russian Piper ruslan-medium",
	 "vits-piper-ru_RU-ruslan-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-ru_RU-ruslan-medium.tar.bz2",
	   ""}}},
	{"Serbian Piper serbski_institut-medium",
	 "vits-piper-sr_RS-serbski_institut-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-sr_RS-serbski_institut-medium.tar.bz2",
	   ""}}},
	{"Slovak Coqui cv",
	 "vits-coqui-sk-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-sk-cv.tar.bz2",
	   ""}}},
	{"Slovak Piper lili-medium",
	 "vits-piper-sk_SK-lili-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-sk_SK-lili-medium.tar.bz2",
	   ""}}},
	{"Slovanian Coqui cv",
	 "vits-coqui-sl-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-sl-cv.tar.bz2",
	   ""}}},
	{"Slovanian Piper artur-medium",
	 "vits-piper-sl_SI-artur-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-sl_SI-artur-medium.tar.bz2",
	   ""}}},
	{"Spanish Coqui css10",
	 "vits-coqui-es-css10",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-es-css10.tar.bz2",
	   ""}}},
	{"Spanish Mimic3 m-ailabs_low",
	 "vits-mimic3-es_ES-m-ailabs_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-es_ES-m-ailabs_low.tar.bz2",
	   ""}}},
	{"Spanish MMS",
	 "vits-mms-spa",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-spa.tar.bz2",
	   ""}}},
	{"Spanish Piper ald-medium",
	 "vits-piper-es_MX-ald-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es_MX-ald-medium.tar.bz2",
	   ""}}},
	{"Spanish Piper carlfm-x_low",
	 "vits-piper-es_ES-carlfm-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es_ES-carlfm-x_low.tar.bz2",
	   ""}}},
	{"Spanish Piper claude-high",
	 "vits-piper-es_MX-claude-high",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es_MX-claude-high.tar.bz2",
	   ""}}},
	{"Spanish Piper davefx-medium",
	 "vits-piper-es_ES-davefx-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es_ES-davefx-medium.tar.bz2",
	   ""}}},
	{"Spanish Piper glados-medium",
	 "vits-piper-es-glados-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es-glados-medium.tar.bz2",
	   ""}}},
	{"Spanish Piper mls_10246-low",
	 "vits-piper-es_ES-mls_10246-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es_ES-mls_10246-low.tar.bz2",
	   ""}}},
	{"Spanish Piper mls_9972-low",
	 "vits-piper-es_ES-mls_9972-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es_ES-mls_9972-low.tar.bz2",
	   ""}}},
	{"Spanish Piper sharvard-medium",
	 "vits-piper-es_ES-sharvard-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-es_ES-sharvard-medium.tar.bz2",
	   ""}}},
	{"Swedish Coqui cv",
	 "vits-coqui-sv-cv",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-sv-cv.tar.bz2",
	   ""}}},
	{"Swedish Piper nst-medium",
	 "vits-piper-sv_SE-nst-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-sv_SE-nst-medium.tar.bz2",
	   ""}}},
	{"Swhaili Piper lanfrica-medium",
	 "vits-piper-sw_CD-lanfrica-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-sw_CD-lanfrica-medium.tar.bz2",
	   ""}}},
	{"Thai MMS",
	 "vits-mms-tha",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-tha.tar.bz2",
	   ""}}},
	{"Tswana Mimic3 google-nwu_low",
	 "vits-mimic3-tn_ZA-google-nwu_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-tn_ZA-google-nwu_low.tar.bz2",
	   ""}}},
	{"Turkish Piper dfki-medium",
	 "vits-piper-tr_TR-dfki-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-tr_TR-dfki-medium.tar.bz2",
	   ""}}},
	{"Turkish Piper fahrettin-medium",
	 "vits-piper-tr_TR-fahrettin-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-tr_TR-fahrettin-medium.tar.bz2",
	   ""}}},
	{"Turkish Piper fettah-medium",
	 "vits-piper-tr_TR-fettah-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-tr_TR-fettah-medium.tar.bz2",
	   ""}}},
	{"Ukranian MMS",
	 "vits-mms-ukr",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mms-ukr.tar.bz2",
	   ""}}},
	{"Ukranian Piper lada-x_low",
	 "vits-piper-uk_UA-lada-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-uk_UA-lada-x_low.tar.bz2",
	   ""}}},
	{"Ukranian Piper ukrainian_tts-medium",
	 "vits-piper-uk_UA-ukrainian_tts-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-uk_UA-ukrainian_tts-medium.tar.bz2",
	   ""}}},
	{"VCTK (109 speakers)",
	 "vits-vctk",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-vctk.tar.bz2",
	   ""}}},
	{"Vietnamese Mimic3 vais1000_low",
	 "vits-mimic3-vi_VN-vais1000_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-mimic3-vi_VN-vais1000_low.tar.bz2",
	   ""}}},
	{"Vietnamese Piper 25hours_single-low",
	 "vits-piper-vi_VN-25hours_single-low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-vi_VN-25hours_single-low.tar.bz2",
	   ""}}},
	{"Vietnamese Piper vais1000-medium",
	 "vits-piper-vi_VN-vais1000-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-vi_VN-vais1000-medium.tar.bz2",
	   ""}}},
	{"Vietnamese Piper vivos-x_low",
	 "vits-piper-vi_VN-vivos-x_low",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-vi_VN-vivos-x_low.tar.bz2",
	   ""}}},
	{"Welsh Piper gwryw_gogleddol-medium",
	 "vits-piper-cy_GB-gwryw_gogleddol-medium",
	 MODEL_TYPE_TTS,
	 {{"https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-cy_GB-gwryw_gogleddol-medium.tar.bz2",
	   ""}}},
};
